### ISSUE TITLE
dexlib2 problem in tiktok 27.3+

### ISSUE THREAD

**Issue by d4rkk3y** [ReVancedTeam/multidexlib2#2]
# Issue description:
There is a problem in dexlib2 which make the dex from tiktok apk version 27.3+ after read and write back become very big. When I tested it, a dex has size 9MB can become 100MB. Afaik, that is the reason why some people report that they can not patch tiktok version 27.3+ https://github.com/revanced/revanced-patches/issues/1358 as multidexlib2 in revanced implement this https://github.com/revanced/multidexlib2/commit/9a31b0b899fda7a19da0b5369cdd539373a30c88. Plus, if they have enough memory the output apk will be very big.
# Possible solution:
There is PR https://github.com/JesusFreke/smali/pull/844 that can fix that problem but for some reason it hasn't been merged for a year.
So is it possible to revanced maintain a dexlib2 repo for multidexlib2 and merge this PR?

**Comment by oSumAtrIX** [comment]
Is the solution confirmed to solve this issue?

**Comment by d4rkk3y** [comment]
> Is the solution confirmed to solve this issue?

Yes, It is. I tested dexlib2 after merge that PR and the issue is solved. I also tested revanced-cli built with that PR in Tiktok 27.8.1, no memory issue and the output apk size is nearly same with the original apk.

**Comment by oSumAtrIX** [comment]
Merged with 115f29248e10488d2f9a2579a18a5b2637a3897f.
